# Generated by Django 3.2.19 on 2023-06-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0002_auto_20230602_0533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='party',
            new_name='Candidate_Number',
        ),
    ]
