# Generated by Django 3.2.19 on 2023-06-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0003_rename_party_candidate_candidate_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.CharField(max_length=12)),
                ('secret_token', models.CharField(max_length=12)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voting_System.elections')),
            ],
        ),
    ]
