# Generated by Django 3.2.19 on 2023-06-02 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0005_expired_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
