# Generated by Django 3.2.19 on 2023-06-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0006_voters_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voters',
            name='secret_token',
            field=models.CharField(max_length=15),
        ),
    ]
