# Generated by Django 3.2.19 on 2023-06-03 07:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0007_alter_voters_secret_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='portfolio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Voting_System.portfolios'),
            preserve_default=False,
        ),
    ]
