# Generated by Django 3.2.19 on 2023-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0009_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Candidate_Number',
            field=models.IntegerField(default=0),
        ),
    ]
