# Generated by Django 3.2.19 on 2023-06-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting_System', '0011_voters_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='sent_sms',
            field=models.BooleanField(default=False, verbose_name='Credentials sent'),
        ),
    ]
